// flow-typed signature: 2319248a198f2ff4d5a3af1d292f072c
// flow-typed version: <<STUB>>/auth0-lock_v11.25.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-lock' {
  declare module.exports: any;
}
