// flow-typed signature: 0cf41c618d5b263a9889740b77d00329
// flow-typed version: <<STUB>>/papaparse_v4.6.3/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'papaparse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'papaparse' {
  declare module.exports: any;
}
