// flow-typed signature: 514f3889cf776ca46f098753412a618e
// flow-typed version: <<STUB>>/react-mapbox-gl_v3.9.2/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mapbox-gl' {
  declare module.exports: any;
}
